name: Delete Commit Records Weekly
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Delete commit records
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git checkout --orphan new_branch
        git commit -m "init"
        git branch -D main
        git branch -m main
        git push -f origin main 
